using Microsoft.Extensions.Logging;
using Po.SeeReview.Core.Interfaces;
using SixLabors.Fonts;
using SixLabors.ImageSharp;
using SixLabors.ImageSharp.Drawing.Processing;
using SixLabors.ImageSharp.PixelFormats;
using SixLabors.ImageSharp.Processing;

namespace Po.SeeReview.Infrastructure.Services;

/// <summary>
/// Service for overlaying readable text onto comic images generated by DALL-E.
/// DALL-E 3 cannot generate correct English letters/words, so this service adds speech bubbles
/// with real readable text after the base image is generated. This ensures all dialogue is legible.
/// </summary>
public class ComicTextOverlayService : IComicTextOverlayService
{
    private readonly IAzureOpenAIService _azureOpenAIService;
    private readonly ILogger<ComicTextOverlayService> _logger;

    public ComicTextOverlayService(
        IAzureOpenAIService azureOpenAIService,
        ILogger<ComicTextOverlayService> logger)
    {
        _azureOpenAIService = azureOpenAIService ?? throw new ArgumentNullException(nameof(azureOpenAIService));
        _logger = logger ?? throw new ArgumentNullException(nameof(logger));
    }

    /// <summary>
    /// Adds per-panel English caption overlays using GPT-generated text.
    /// Each panel gets its own caption box at the top, covering any garbled AI-rendered text.
    /// </summary>
    public async Task<byte[]> AddTextOverlayAsync(byte[] imageBytes, string narrative, int panelCount)
    {
        if (imageBytes == null || imageBytes.Length == 0)
            throw new ArgumentException("Image bytes cannot be empty", nameof(imageBytes));

        if (string.IsNullOrWhiteSpace(narrative))
            throw new ArgumentException("Narrative cannot be empty", nameof(narrative));

        _logger.LogInformation("Adding per-panel text overlay to {PanelCount}-panel comic", panelCount);

        try
        {
            // Use GPT to generate unique, naturally flowing English for each panel
            var dialogues = await _azureOpenAIService.GeneratePanelDialogueAsync(narrative, panelCount);

            using var image = Image.Load<Rgba32>(imageBytes);
            var font = GetComicFont(16);
            var panelBounds = GetPanelBounds(image.Width, image.Height, panelCount);

            for (int i = 0; i < Math.Min(dialogues.Count, panelBounds.Count); i++)
            {
                if (!string.IsNullOrWhiteSpace(dialogues[i]))
                    DrawPanelCaption(image, dialogues[i], panelBounds[i], font);
            }

            using var outputStream = new MemoryStream();
            image.SaveAsPng(outputStream);

            _logger.LogInformation("Drew {Count} panel caption(s) onto comic", panelBounds.Count);
            return outputStream.ToArray();
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Failed to add text overlay, returning original image");
            return imageBytes;
        }
    }

    /// <summary>
    /// Returns approximate bounding rectangle for each panel.
    /// Matches the layouts requested by GeminiComicService prompts.
    /// </summary>
    private static List<RectangleF> GetPanelBounds(int width, int height, int panelCount)
    {
        const int Gutter = 6;
        var bounds = new List<RectangleF>();

        switch (panelCount)
        {
            case 1:
                bounds.Add(new RectangleF(0, 0, width, height));
                break;
            case 2:
                // Two panels stacked vertically
                var h2 = (height - Gutter) / 2f;
                bounds.Add(new RectangleF(0, 0, width, h2));
                bounds.Add(new RectangleF(0, h2 + Gutter, width, h2));
                break;
            case 3:
                // Three panels side-by-side horizontally
                var w3 = (width - 2 * Gutter) / 3f;
                bounds.Add(new RectangleF(0, 0, w3, height));
                bounds.Add(new RectangleF(w3 + Gutter, 0, w3, height));
                bounds.Add(new RectangleF(2 * (w3 + Gutter), 0, w3, height));
                break;
            default:
                // Four panels in 2x2 grid
                var w4 = (width - Gutter) / 2f;
                var h4 = (height - Gutter) / 2f;
                bounds.Add(new RectangleF(0, 0, w4, h4));
                bounds.Add(new RectangleF(w4 + Gutter, 0, w4, h4));
                bounds.Add(new RectangleF(0, h4 + Gutter, w4, h4));
                bounds.Add(new RectangleF(w4 + Gutter, h4 + Gutter, w4, h4));
                break;
        }

        return bounds;
    }

    /// <summary>
    /// Draws a classic comic-style yellow caption box at the top of the panel.
    /// Covers any garbled AI-rendered text while providing a clean, readable overlay.
    /// </summary>
    private void DrawPanelCaption(Image<Rgba32> image, string text, RectangleF panelBounds, Font font)
    {
        const int Padding = 6;
        var maxWrappingWidth = panelBounds.Width - Padding * 2 - 8;
        var origin = new PointF(
            panelBounds.X + panelBounds.Width / 2f,
            panelBounds.Y + Padding);

        var textOptions = new RichTextOptions(font)
        {
            Origin = origin,
            HorizontalAlignment = HorizontalAlignment.Center,
            VerticalAlignment = VerticalAlignment.Top,
            WrappingLength = maxWrappingWidth
        };

        var textBounds = TextMeasurer.MeasureBounds(text, textOptions);
        var bgRect = new RectangleF(
            textBounds.X - Padding,
            textBounds.Y - Padding,
            textBounds.Width + Padding * 2,
            textBounds.Height + Padding * 2);

        image.Mutate(ctx =>
        {
            // Classic comic yellow caption box
            ctx.Fill(new Color(new Rgba32(255, 255, 180, 245)), bgRect);
            ctx.Draw(Color.Black, 1.5f, bgRect);
            ctx.DrawText(textOptions, text, Color.Black);
        });

        _logger.LogDebug("Drew panel caption at ({X},{Y}): {Text}", panelBounds.X, panelBounds.Y, text);
    }

    /// <summary>
    /// Gets a comic-style font for text rendering
    /// </summary>
    private Font GetComicFont(int size)
    {
        try
        {
            var families = SystemFonts.Families.ToList();
            if (families.Count == 0)
            {
                _logger.LogWarning("No system fonts available, text overlay will be skipped");
                throw new InvalidOperationException("No fonts available");
            }
            
            // Try to use Comic Sans MS, Arial, DejaVu, Liberation, or fall back to first available font
            var fontFamily = families.FirstOrDefault(f => 
                f.Name.Contains("Comic", StringComparison.OrdinalIgnoreCase) ||
                f.Name.Contains("Arial", StringComparison.OrdinalIgnoreCase) ||
                f.Name.Contains("DejaVu", StringComparison.OrdinalIgnoreCase) ||
                f.Name.Contains("Liberation", StringComparison.OrdinalIgnoreCase));

            var selectedFamily = fontFamily.Name != null ? fontFamily : families.First();
            return selectedFamily.CreateFont(size, FontStyle.Bold);
        }
        catch (Exception ex)
        {
            _logger.LogWarning(ex, "Failed to get font, will skip text overlay");
            throw;
        }
    }
}
